spryker/cypress-tests

cypress/support/commands.ts, cypress/support/pages/mp/agent-dashboard/agent-dashboard-page.ts
=> Render dynamic fixture error body.

cypress/fixtures/suite/backoffice/return-management/dynamic-return-creation.json, cypress/support/types/backoffice/return-management.ts, package-lock.json, package.json
=> Added additional quotes by dynamic fixtures.

docker-compose.cypress.yml
=> Adjusted docker-compose version.

cypress/fixtures/b2b-mp/backoffice/merchant-b2b-contract-requests/dynamic-request-management.json, cypress/fixtures/b2b-mp/backoffice/merchant-b2b-contract-requests/static-request-management.json, cypress/fixtures/b2b-mp/mp/merchant-b2b-contract-requests/dynamic-request-management.json, cypress/fixtures/b2b-mp/mp/merchant-b2b-contract-requests/static-request-management.json, cypress/fixtures/b2b-mp/yves/merchant-b2b-contract-requests/dynamic-request-creation.json, cypress/fixtures/b2b-mp/yves/merchant-b2b-contract-requests/dynamic-request-management.json, cypress/fixtures/b2b-mp/yves/merchant-b2b-contract-requests/static-request-creation.json, cypress/fixtures/b2b-mp/yves/merchant-b2b-contract-requests/static-request-management.json, cypress/support/pages/yves/cart/repositories/b2b-mp-cart-repository.ts, cypress/support/pages/yves/catalog/repositories/b2b-mp-catalog-repository.ts, cypress/support/pages/yves/company/merchant-relation-request/create/merchant-relation-request-create-page.ts, cypress/support/pages/yves/company/merchant-relation-request/create/repositories/b2b-mp-merchant-relation-request-create-repository.ts, cypress/support/pages/yves/company/merchant-relation-request/details/repositories/b2b-mp-merchant-relation-request-details-repository.ts, cypress/support/pages/yves/company/merchant-relation-request/index/merchant-relation-request-index-page.ts, cypress/support/pages/yves/company/merchant-relation-request/index/repositories/b2b-mp-merchant-relation-request-index-repository.ts, cypress/support/pages/yves/company/user/select/company-user-select-page.ts, cypress/support/pages/yves/company/user/select/repositories/b2b-mp-company-user-select-repository.ts, cypress/support/pages/yves/login/repositories/b2b-mp-login-repository.ts, cypress/support/pages/yves/merchant/repositories/b2b-mp-merchant-repository.ts, cypress/support/pages/yves/product/repositories/b2b-mp-product-repository.ts, cypress/support/utils/inversify/inversify.config.ts, package-lock.json, package.json
Ticket: https://spryker.atlassian.net/browse/CC-33396
=> CC-33374: B2B-MP integration of MR requests.

.env.dynamic-store.example
https://spryker.atlassian.net/browse/CC-33312
=> CC-33312: Added dynamic example .env file.

Dockerfile, cypress.config.ts, docker-compose.cypress.yml
https://spryker.atlassian.net/browse/CC-33312
=> Adjusted docker files.

.github/workflows/post-deploy-workflow.yml
Epic link: https://spryker.atlassian.net/browse/CC-33306
Task: https://spryker.atlassian.net/browse/CC-33771
Description:
Added the optional control for enabling basic authentication.
- ADR: https://spryker.atlassian.net/wiki/spaces/CORE/pages/4242243587/WIP+Release+Automation+initiative.
=> CC-33771: Added the optional control for enabling basic authentication.

.github/workflows/post-deploy-workflow.yml, docker-compose.cypress-post-deploy-workflow.yml, package.json
Epic link: https://spryker.atlassian.net/browse/CC-33306
Task: https://spryker.atlassian.net/browse/CC-33771
Description:
- Added the new cypress command "cy:smoke:outdated" - for previous release.
=> CC-33771: Added "cy:smoke:outdated" command for the previous release.

.github/workflows/post-deploy-workflow.yml, post-deploy-workflow/post-deploy-workflow-handler.sh
Epic link: https://spryker.atlassian.net/browse/CC-33306
Task: https://spryker.atlassian.net/browse/CC-33771
Description:
- Fixed the setup of the "ENV_REPOSITORY_ID".
=> CC-33771: Fixed the setup of the "ENV_REPOSITORY_ID".

cypress/support/pages/yves/comment/cart/repositories/b2b-comment-cart-repository.ts, cypress/support/pages/yves/comment/cart/repositories/b2b-mp-comment-cart-repository.ts
Epic link: https://spryker.atlassian.net/browse/CC-16986
Task: https://spryker.atlassian.net/browse/CC-33480
Description:
Update remove comment button selector.
=> CC-16986: Update Cart Without Reload

cypress/e2e/backoffice/return-management/return-creation.cy.ts, cypress/e2e/yves/cart/cart-item-note-management.cy.ts, cypress/e2e/yves/cart/change-cart-item-quantity.cy.ts, cypress/e2e/yves/cart/remove-cart-item.cy.ts, package-lock.json, package.json
=> Enabled Yves-cart epic tests.

cypress/e2e/backoffice/order-management/custom-order-reference-management.cy.ts, cypress/e2e/yves/cart/cart-item-note-management.cy.ts, cypress/e2e/yves/cart/change-cart-item-quantity.cy.ts, cypress/e2e/yves/cart/remove-cart-item.cy.ts, cypress/fixtures/b2b-mp/backoffice/order-management/dynamic-custom-order-reference-management.json, cypress/fixtures/b2b-mp/backoffice/order-management/static-custom-order-reference-management.json, cypress/fixtures/b2b-mp/yves/cart/dynamic-cart-item-note-management.json, cypress/fixtures/b2b-mp/yves/cart/dynamic-change-cart-item-quantity.json, cypress/fixtures/b2b-mp/yves/cart/dynamic-remove-cart-item.json, cypress/fixtures/b2b-mp/yves/cart/static-cart-item-note-management.json, cypress/fixtures/b2b-mp/yves/cart/static-change-cart-item-quantity.json, cypress/fixtures/b2b-mp/yves/cart/static-remove-cart-item.json, cypress/fixtures/b2b/backoffice/order-management/dynamic-custom-order-reference-management.json, cypress/fixtures/b2b/backoffice/order-management/static-custom-order-reference-management.json, cypress/fixtures/b2b/yves/cart/dynamic-cart-item-note-management.json, cypress/fixtures/b2b/yves/cart/dynamic-change-cart-item-quantity.json, cypress/fixtures/b2b/yves/cart/dynamic-remove-cart-item.json, cypress/fixtures/b2b/yves/cart/static-cart-item-note-management.json, cypress/fixtures/b2b/yves/cart/static-change-cart-item-quantity.json, cypress/fixtures/b2b/yves/cart/static-remove-cart-item.json, cypress/support/pages/yves/cart/cart-page.ts, cypress/support/pages/yves/cart/cart-repository.ts, cypress/support/pages/yves/cart/repositories/b2b-cart-repository.ts, cypress/support/pages/yves/cart/repositories/b2b-mp-cart-repository.ts, cypress/support/pages/yves/cart/repositories/b2c-cart-repository.ts, cypress/support/pages/yves/cart/repositories/b2c-mp-cart-repository.ts, cypress/support/pages/yves/cart/repositories/suite-cart-repository.ts
=> Enabled Yves-cart epic tests for b2b demo shops.

cypress/e2e/yves/merchant-b2b-contract-requests/request-creation.cy.ts, cypress/e2e/yves/merchant-b2b-contract-requests/request-management.cy.ts
https://spryker.atlassian.net/browse/CC-33810
=> CC-33810: Fixed flaky tests.

cypress/e2e/yves/merchant-b2b-contract-requests/request-creation.cy.ts, cypress/e2e/yves/merchant-b2b-contract-requests/request-management.cy.ts
=> Reverted changes.

cypress/e2e/backoffice/order-management/order-creation.cy.ts, cypress/e2e/mp/marketplace-merchant-commission/commission-calculation.cy.ts, cypress/fixtures/suite/mp/marketplace-merchant-commission/dynamic-commission-calculation.json, cypress/fixtures/suite/mp/marketplace-merchant-commission/static-commission-calculation.json, cypress/support/pages/backoffice/sales/detail/sales-detail-page.ts, cypress/support/pages/mp/mp-page.ts, cypress/support/pages/mp/sales/sales-orders-page.ts, cypress/support/pages/mp/sales/sales-orders-repository.ts, cypress/support/pages/yves/product/product-page.ts, cypress/support/pages/yves/product/repositories/suite-product-repository.ts, cypress/support/types/mp/index.ts, cypress/support/types/mp/marketplace-merchant-commission.ts, cypress/support/types/mp/shared/address.ts, cypress/support/types/mp/shared/index.ts, package-lock.json, package.json
https://spryker.atlassian.net/browse/CC-33790
=> CC-33790: Commissions Cypress Test.

cypress/fixtures/suite/mp/marketplace-merchant-commission/dynamic-commission-calculation.json
=> Adjusted merchant-commission fixtures.

cypress/e2e/mp/marketplace-merchant-commission/commission-calculation.cy.ts
=> Adjusted wait time.

cypress/support/pages/yves/company/merchant-relation-request/index/repositories/b2b-merchant-relation-request-index-repository.ts, cypress/support/pages/yves/company/merchant-relation-request/index/repositories/b2b-mp-merchant-relation-request-index-repository.ts, cypress/support/pages/yves/company/merchant-relation-request/index/repositories/b2c-merchant-relation-request-index-repository.ts, cypress/support/pages/yves/company/merchant-relation-request/index/repositories/b2c-mp-merchant-relation-request-index-repository.ts, cypress/support/pages/yves/company/merchant-relation-request/index/repositories/suite-merchant-relation-request-index-repository.ts
https://spryker.atlassian.net/browse/CC-33977
Fixed related to https://github.com/spryker/spryker-shop/pull/2501
=> CC-33977: Fixed merchant relation request locators

cypress/e2e/mp/marketplace-merchant-commission/commission-calculation.cy.ts, cypress/fixtures/b2b-mp/mp/marketplace-merchant-commission/dynamic-commission-calculation.json, cypress/fixtures/b2b-mp/mp/marketplace-merchant-commission/static-commission-calculation.json, cypress/fixtures/b2c-mp/mp/marketplace-merchant-commission/dynamic-commission-calculation.json, cypress/fixtures/b2c-mp/mp/marketplace-merchant-commission/static-commission-calculation.json, cypress/support/pages/yves/product/repositories/b2b-mp-product-repository.ts, package-lock.json, package.json
=> Adjusted fixtures in order to enable commission tests for demoshops.

cypress/support/pages/yves/company/merchant-relation-request/index/repositories/b2b-mp-merchant-relation-request-index-repository.ts
=> Small adjustments.

cypress/fixtures/b2b-mp/backoffice/order-management/dynamic-custom-order-reference-management.json, cypress/fixtures/b2b-mp/backoffice/order-management/dynamic-order-creation.json, cypress/fixtures/b2b-mp/yves/comments/dynamic-cart-comments.json, cypress/fixtures/b2b/backoffice/order-management/dynamic-custom-order-reference-management.json, cypress/fixtures/b2b/backoffice/order-management/dynamic-order-creation.json, cypress/fixtures/b2b/backoffice/return-management/dynamic-return-creation.json, cypress/fixtures/b2b/yves/cart/dynamic-cart-item-note-management.json, cypress/fixtures/b2b/yves/cart/dynamic-change-cart-item-quantity.json, cypress/fixtures/b2b/yves/cart/dynamic-remove-cart-item.json, cypress/fixtures/b2b/yves/checkout/dynamic-basic-checkout.json, cypress/fixtures/b2b/yves/comments/dynamic-cart-comments.json, cypress/fixtures/b2c-mp/yves/cart/dynamic-change-cart-item-quantity.json, cypress/fixtures/b2c-mp/yves/cart/dynamic-remove-cart-item.json, cypress/fixtures/b2c/backoffice/order-management/dynamic-order-creation.json, cypress/fixtures/b2c/backoffice/return-management/dynamic-return-creation.json, cypress/fixtures/b2c/yves/cart/dynamic-change-cart-item-quantity.json, cypress/fixtures/b2c/yves/cart/dynamic-remove-cart-item.json, cypress/fixtures/b2c/yves/checkout/dynamic-basic-checkout.json, cypress/fixtures/suite/backoffice/order-management/dynamic-custom-order-reference-management.json, cypress/fixtures/suite/backoffice/order-management/dynamic-order-creation.json, cypress/fixtures/suite/backoffice/return-management/dynamic-return-creation.json, cypress/fixtures/suite/yves/cart/dynamic-cart-item-note-management.json, cypress/fixtures/suite/yves/cart/dynamic-change-cart-item-quantity.json, cypress/fixtures/suite/yves/cart/dynamic-remove-cart-item.json, cypress/fixtures/suite/yves/checkout/dynamic-basic-checkout.json, cypress/fixtures/suite/yves/comments/dynamic-cart-comments.json, cypress/support/pages/yves/catalog/catalog-page.ts
https://spryker.atlassian.net/browse/CC-34484
=> CC-34484: Session locking issue after recent integration on B2C and B2C Marketplace demo shops.

cypress/support/pages/yves/company/merchant-relation-request/index/repositories/b2b-merchant-relation-request-index-repository.ts
=> Adjusted Relation Request Table name.

cypress/e2e/mp/marketplace-product-concretes/product-concrete-management.cy.ts, cypress/fixtures/b2b-mp/mp/marketplace-product-concretes/dynamic-product-concrete-management.json, cypress/fixtures/b2b-mp/mp/marketplace-product-concretes/static-product-concrete-management.json, cypress/fixtures/b2c-mp/mp/marketplace-product-concretes/dynamic-product-concrete-management.json, cypress/fixtures/b2c-mp/mp/marketplace-product-concretes/static-product-concrete-management.json, cypress/fixtures/suite/mp/marketplace-product-concretes/dynamic-product-concrete-management.json, cypress/fixtures/suite/mp/marketplace-product-concretes/static-product-concrete-management.json, cypress/support/pages/mp/index.ts, cypress/support/pages/mp/variants/variants-page.ts, cypress/support/pages/mp/variants/variants-repository.ts, cypress/support/types/mp/index.ts, cypress/support/types/mp/marketplace-product-concretes.ts
- Epic Ticket: https://spryker.atlassian.net/browse/CC-34423
- Task Ticket: https://spryker.atlassian.net/browse/CC-34481
=> CC-34423 Add MP variants test case

cypress/e2e/smoke/merchant-portal/login.cy.ts, cypress/e2e/yves/product/publish-and-synchronize.cy.ts, cypress/fixtures/b2b-mp/smoke/merchant-portal/static-login.json, cypress/fixtures/b2b-mp/yves/product/dynamic-publish-and-synchronize.json, cypress/fixtures/b2b-mp/yves/product/static-publish-and-synchronize.json, cypress/fixtures/b2b/yves/product/dynamic-publish-and-synchronize.json, cypress/fixtures/b2b/yves/product/static-publish-and-synchronize.json, cypress/fixtures/b2c-mp/smoke/merchant-portal/static-login.json, cypress/fixtures/b2c-mp/yves/product/dynamic-publish-and-synchronize.json, cypress/fixtures/b2c-mp/yves/product/static-publish-and-synchronize.json, cypress/fixtures/b2c/yves/product/dynamic-publish-and-synchronize.json, cypress/fixtures/b2c/yves/product/static-publish-and-synchronize.json, cypress/fixtures/suite/smoke/merchant-portal/static-login.json, cypress/fixtures/suite/yves/product/dynamic-publish-and-synchronize.json, cypress/fixtures/suite/yves/product/static-publish-and-synchronize.json, cypress/support/types/smoke/index.ts, cypress/support/types/smoke/merchant-portal.ts, cypress/support/types/yves/index.ts, cypress/support/types/yves/product.ts
- Ticket: https://spryker.atlassian.net/browse/CC-33971
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit …
=> CC-33971: Added missing P&S + mp tests.

cypress/fixtures/b2b-mp/yves/comments/dynamic-cart-comments.json, cypress/fixtures/b2b-mp/yves/product/dynamic-publish-and-synchronize.json, cypress/fixtures/b2b/yves/comments/dynamic-cart-comments.json, cypress/fixtures/b2b/yves/product/dynamic-publish-and-synchronize.json, cypress/support/pages/yves/company/merchant-relation-request/index/repositories/b2b-merchant-relation-request-index-repository.ts, cypress/support/pages/yves/company/merchant-relation-request/index/repositories/b2b-mp-merchant-relation-request-index-repository.ts
=> Release 202410.01 fixes.

cypress/e2e/backoffice/category/category-edit.cy.ts, cypress/fixtures/b2b-mp/backoffice/category/static-category-edit.json, cypress/fixtures/b2c-mp/backoffice/category/static-category-edit.json, cypress/fixtures/b2c/backoffice/category/static-category-edit.json, cypress/fixtures/suite/backoffice/category/static-category-edit.json, cypress/support/pages/backoffice/catalog/category/edit/category-edit-page.ts, cypress/support/pages/backoffice/catalog/category/edit/category-edit-repository.ts, cypress/support/pages/backoffice/catalog/category/list/category-list-page.ts, cypress/support/pages/backoffice/catalog/category/list/category-list-repository.ts, cypress/support/pages/backoffice/index.ts, cypress/support/types/backoffice/category-edit.ts, cypress/support/types/backoffice/index.ts, cypress/support/types/backoffice/order-management.ts
- Developer(s): @aleksandr-velikanov
- Ticket: https://spryker.atlassian.net/browse/FRW-6354
- RG: https://release.spryker.com/release-groups/view/5562
Improvements
- Added Category Edit e2e test
- Added CategoryListPage and CategoryListRepository
=> FRW-6354 Added a help message to the store selector field. 

cypress/e2e/mp/marketplace-product-attributes/product-attribute-management.cy.ts, cypress/fixtures/b2b-mp/mp/marketplace-product-attributes/dynamic-product-attribute-management.json, cypress/fixtures/b2b-mp/mp/marketplace-product-attributes/static-product-attribute-management.json, cypress/fixtures/b2c-mp/mp/marketplace-product-attributes/dynamic-product-attribute-management.json, cypress/fixtures/b2c-mp/mp/marketplace-product-attributes/static-product-attribute-management.json, cypress/fixtures/suite/mp/marketplace-product-attributes/dynamic-product-attribute-management.json, cypress/fixtures/suite/mp/marketplace-product-attributes/static-product-attribute-management.json, cypress/support/pages/mp/products/products-page.ts, cypress/support/pages/mp/products/products-repository.ts, cypress/support/types/mp/index.ts, cypress/support/types/mp/marketplace-products.ts
Ticket: https://spryker.atlassian.net/browse/SUPESC-871
=> SUPESC-871 Changed field type for the attributes in the merchant portal.

.env.dynamic-store.example, .env.example, .gitignore, cypress.config.ts, cypress/support/pages/yves/cart/repositories/suite-cart-repository.ts
Ticket: https://spryker.atlassian.net/browse/FRW-9367
=> FRW-7936 Fixed tests

package.json
=> ACP-4619: Fixed the shipment expenses handling.

package.json
=> CC-33970: Added the "cy:smoke:demo" command for the demo environments.

cypress/e2e/yves/catalog/product-search-dms.cy.ts
Ticket: https://spryker.atlassian.net/browse/CC-35021
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You can take it from commits list of master branch before you submit a PR.
=> Fixed flaky tests in DMS.

cypress/e2e/backoffice/order-management/order-creation-dms.cy.ts, cypress/e2e/backoffice/return-management/return-creation.cy.ts, cypress/e2e/mp/marketplace-order-management/order-creation-dms.cy.ts, cypress/e2e/smoke/order-management/dummy-payment-oms-flow.cy.ts, cypress/e2e/yves/order-amendment/order-amendment-cancel.cy.ts, cypress/e2e/yves/order-amendment/order-amendment-start.cy.ts, cypress/support/commands.ts, cypress/support/index.d.ts, cypress/support/pages/backoffice/sales/detail/sales-detail-page.ts, cypress/support/pages/yves/customer/order/order-details-page.ts, cypress/support/pages/yves/customer/order/order-details-repository.ts, cypress/support/pages/yves/customer/order/repositories/b2b-mp-order-details-repository.ts, cypress/support/pages/yves/customer/order/repositories/b2b-order-details-repository.ts, cypress/support/pages/yves/customer/order/repositories/b2c-mp-order-details-repository.ts, cypress/support/pages/yves/customer/order/repositories/b2c-order-details-repository.ts, cypress/support/pages/yves/customer/order/repositories/suite-order-details-repository.ts
Ticket: https://spryker.atlassian.net/browse/CC-34502
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You can take it from commits list of master branch before you submit a PR.
=> Feature/cc 34502/dev order amendment finalisation

cypress/e2e/smoke/order-management/dummy-payment-oms-flow.cy.ts
=> Removed OMS grace period trigger from smoke test.

cypress.config.ts, cypress/e2e/backoffice/claim/claim-view.cy.ts, cypress/e2e/yves/claim/claim.cy.ts, cypress/fixtures/suite/backoffice/claim/dynamic-claim-view.json, cypress/fixtures/suite/yves/claim/dynamic-claim.json, cypress/fixtures/suite/yves/claim/static-claim.json, cypress/support/pages/backoffice/claim/claim-detail-page.ts, cypress/support/pages/backoffice/claim/claim-list-page.ts, cypress/support/pages/backoffice/index.ts, cypress/support/pages/yves/claim/claim-create-page.ts, cypress/support/pages/yves/claim/claim-detail-page.ts, cypress/support/pages/yves/claim/claim-list-page.ts, cypress/support/pages/yves/claim/claim-order-page.ts, cypress/support/pages/yves/claim/claim-repository.ts, cypress/support/pages/yves/claim/repositories/suite-claim-repository.ts, cypress/support/scenarios/yves/customer-logout-scenario.ts, cypress/support/scenarios/yves/index.ts, cypress/support/types/backoffice/claim.ts, cypress/support/types/yves/claim.ts, cypress/support/utils/inversify/inversify.config.ts
https://spryker.atlassian.net/browse/SSP-272
=> SSP-272 Cypress tests Storefront [State machine, permissions]

cypress/support/pages/yves/product/product-page.ts, package-lock.json, package.json
https://spryker.atlassian.net/browse/CC-35103
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You can take it from commits list of master branch before you submit a PR.
=> CC-35103: Fixed b2c-mp smoke flaky tests.

cypress/e2e/backoffice/return-management/return-creation.cy.ts
=> Skipped grace-period state for demoshop tests.

cypress/support/pages/yves/company/company-role/create/repositories/b2c-company-role-create-repository.ts, cypress/support/pages/yves/company/company-role/create/repositories/b2c-mp-company-role-create-repository.ts, cypress/support/pages/yves/company/company-role/index/repositories/b2c-company-role-index-repository.ts, cypress/support/pages/yves/company/company-role/index/repositories/b2c-mp-company-role-index-repository.ts, cypress/support/utils/inversify/inversify.config.ts
=> Added missing repos to inversify container.

cypress/e2e/backoffice/ssp-file-management/ssp-file-management.cy.ts, cypress/support/pages/backoffice/ssp-file-management/add/ssp-file-management-add-page.ts, cypress/support/pages/yves/ssp-file-management/list/ssp-file-management-list-page.ts, cypress/support/pages/yves/ssp-file-management/list/ssp-file-management-list-repository.ts, cypress/support/types/backoffice/ssp-file-management.ts
=> SSP-2: fix selectors

cypress.config.ts, cypress/e2e/yves/core/locale-switching.cy.ts, cypress/fixtures/b2b-mp/mp/marketplace-agent-assist/dynamic-agent-merchant-portal.json, cypress/fixtures/b2b-mp/mp/marketplace-merchant-commission/dynamic-commission-calculation.json, cypress/fixtures/b2b-mp/mp/merchant-b2b-contract-requests/dynamic-request-management.json, cypress/fixtures/b2b-mp/yves/core/dynamic-locale-switching.json, cypress/fixtures/b2b-mp/yves/merchant-b2b-contract-requests/dynamic-request-creation.json, cypress/fixtures/b2b-mp/yves/merchant-b2b-contract-requests/dynamic-request-management.json, cypress/fixtures/b2b/yves/core/dynamic-locale-switching.json, cypress/fixtures/b2c-mp/backoffice/order-management/dynamic-order-creation.json, cypress/fixtures/b2c-mp/mp/marketplace-agent-assist/dynamic-agent-merchant-portal.json, cypress/fixtures/b2c-mp/mp/marketplace-merchant-commission/dynamic-commission-calculation.json, cypress/fixtures/b2c-mp/yves/core/dynamic-locale-switching.json, cypress/fixtures/b2c/yves/core/dynamic-locale-switching.json, cypress/fixtures/suite/mp/marketplace-agent-assist/dynamic-agent-merchant-portal.json, cypress/fixtures/suite/mp/marketplace-merchant-commission/dynamic-commission-calculation.json, cypress/fixtures/suite/mp/merchant-b2b-contract-requests/dynamic-request-management.json, cypress/fixtures/suite/yves/core/dynamic-locale-switching.json, cypress/fixtures/suite/yves/merchant-b2b-contract-requests/dynamic-request-creation.json, cypress/fixtures/suite/yves/merchant-b2b-contract-requests/dynamic-request-management.json, cypress/support/commands.ts, cypress/support/scenarios/backoffice/assign-store-to-shipment-method-scenario.ts, cypress/support/types/yves/locale.ts, package-lock.json, package.json
https://spryker.atlassian.net/browse/CC-35273
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You can take it from commits list of master branch before you submit a PR.
=> CC-35273: Fixed issue with locale-switching test.

cypress/support/pages/yves/company/user/manage/repositories/b2c-manage-company-role-user-repository.ts, cypress/support/pages/yves/company/user/manage/repositories/b2c-mp-manage-company-role-user-repository.ts, cypress/support/utils/inversify/inversify.config.ts, package-lock.json
=> Fixed company account tests.

cypress/fixtures/b2b/yves/company-account/dynamic-manage-company-user-role.json, cypress/support/pages/yves/company/user/manage/manage-company-role-user-page.ts
Ticket: https://spryker.atlassian.net/browse/CC-34127
Contains fixes for a missing permission (b2b).
=> FRW-9435 Added SeeCompanyMenuPermissionPlugin permission.

cypress/e2e/yves/ssp-asset/ssp-asset.cy.ts, cypress/fixtures/suite/yves/ssp-asset/dynamic-ssp-asset.json, cypress/fixtures/suite/yves/ssp-inquiry/dynamic-ssp-inquiry.json, cypress/support/pages/yves/ssp-asset/repositories/suite-ssp-asset-repository.ts, cypress/support/pages/yves/ssp-asset/ssp-asset-detail-page.ts, cypress/support/pages/yves/ssp-asset/ssp-asset-list-page.ts, cypress/support/pages/yves/ssp-asset/ssp-asset-repository.ts, cypress/support/types/yves/ssp-asset.ts
=> Feature/ssp 451/asset permissions

cypress/e2e/yves/ssp-service/ssp-service.cy.ts, cypress/support/pages/yves/ssp-service/repositories/suite-ssp-service-repository.ts, cypress/support/pages/yves/ssp-service/ssp-service-list-page.ts, cypress/support/pages/yves/ssp-service/ssp-service-repository.ts
https://spryker.atlassian.net/browse/SSP-340
=> SSP-340 Reschedule service cypress tests.

cypress/e2e/yves/ssp-service/ssp-service.cy.ts
https://spryker.atlassian.net/browse/SSP-836
=> SSP-836 Disabled flickery test.

cypress/support/pages/yves/ssp-asset/repositories/suite-ssp-asset-repository.ts, cypress/support/pages/yves/ssp-file-management/list/ssp-file-management-list-repository.ts, cypress/support/pages/yves/ssp-inquiry/repositories/suite-ssp-inquiry-repository.ts, cypress/support/pages/yves/ssp-service/repositories/suite-ssp-service-repository.ts
- https://spryker.atlassian.net/browse/SSP-696
=> SSP-696: SSP features fix selectors

cypress/e2e/backoffice/ssp-file-management/ssp-file-management.cy.ts, cypress/e2e/yves/ssp-file-management/ssp-file-management.cy.ts, cypress/fixtures/suite/backoffice/ssp-asset-management/dynamic-ssp-asset-management.json, cypress/fixtures/suite/yves/ssp-asset/dynamic-ssp-asset.json, cypress/fixtures/suite/yves/ssp-file-management/dynamic-ssp-file-management.json, cypress/fixtures/suite/yves/ssp-inquiry/dynamic-ssp-inquiry.json, cypress/support/pages/backoffice/ssp-file-management/attach/ssp-file-management-attach-page.ts, cypress/support/pages/backoffice/ssp-file-management/attach/ssp-file-management-attach-repository.ts, cypress/support/pages/yves/index.ts, cypress/support/pages/yves/ssp-asset/repositories/suite-ssp-asset-repository.ts, cypress/support/pages/yves/ssp-file-management/ssp-file-management-download-page.ts, cypress/support/pages/yves/ssp-file-management/ssp-file-management-list-page.ts, cypress/support/pages/yves/ssp-file-management/ssp-file-management-repository.ts, cypress/support/types/yves/ssp-file-management.ts
=> SSP-4: cypress tests for attach file to asset

cypress/fixtures/suite/yves/ssp-dashboard-management/dynamic-ssp-dashboard-management.json
=> SSP-4: fix tests

cypress/e2e/yves/order-amendment/order-amendment-cancel.cy.ts, cypress/e2e/yves/order-amendment/order-amendment-start.cy.ts, cypress/fixtures/suite/yves/order-amendment/dynamic-order-amendment-start.json, cypress/support/pages/yves/cart/cart-page.ts, cypress/support/pages/yves/cart/cart-repository.ts, cypress/support/pages/yves/cart/repositories/b2b-cart-repository.ts, cypress/support/pages/yves/cart/repositories/b2b-mp-cart-repository.ts, cypress/support/pages/yves/cart/repositories/b2c-cart-repository.ts, cypress/support/pages/yves/cart/repositories/b2c-mp-cart-repository.ts, cypress/support/pages/yves/cart/repositories/suite-cart-repository.ts, cypress/support/pages/yves/customer/order/order-details-page.ts, cypress/support/pages/yves/customer/order/order-details-repository.ts, cypress/support/pages/yves/customer/order/repositories/b2b-mp-order-details-repository.ts, cypress/support/pages/yves/customer/order/repositories/b2b-order-details-repository.ts, cypress/support/pages/yves/customer/order/repositories/b2c-mp-order-details-repository.ts, cypress/support/pages/yves/customer/order/repositories/b2c-order-details-repository.ts, cypress/support/pages/yves/customer/order/repositories/suite-order-details-repository.ts, cypress/support/pages/yves/multi-cart/multi-cart-page.ts, cypress/support/pages/yves/multi-cart/multi-cart-repository.ts, cypress/support/pages/yves/multi-cart/repositories/b2b-mp-multi-cart-repository.ts, cypress/support/pages/yves/multi-cart/repositories/b2b-multi-cart-repository.ts, cypress/support/pages/yves/multi-cart/repositories/b2c-mp-multi-cart-repository.ts, cypress/support/pages/yves/multi-cart/repositories/b2c-multi-cart-repository.ts, cypress/support/pages/yves/multi-cart/repositories/suite-multi-cart-repository.ts, cypress/support/types/yves/order-amendment.ts
- https://spryker.atlassian.net/browse/CC-34515
=> CC-34515 Enable Order Amendment for features connected to Cart (Multi-Cart).

cypress/fixtures/suite/yves/ssp-service/dynamic-ssp-service.json
https://spryker.atlassian.net/browse/SSP-1003
=> SSP-776 Fixed cypress tests.

cypress/fixtures/suite/yves/ssp-dashboard-management/dynamic-ssp-dashboard-management.json, cypress/support/pages/yves/ssp-service/repositories/b2b-mp-ssp-service-repository.ts
- Ticket: https://spryker.atlassian.net/browse/SSP-1002
Reference all core PRs for auto-link back-references.
Core PRs
- https://github.com/spryker/spryker/pull/11558
RG: https://release.spryker.com/release-groups/view/5881
=> SSP-1029 Fix ssp dashboard flickery tests.

cypress/support/pages/backoffice/index/index-page.ts, cypress/support/scenarios/backoffice/user-login-scenario.ts, cypress/support/scenarios/backoffice/user-mfa-login-scenario.ts
Ticket: https://spryker.atlassian.net/browse/FRW-10522
=> FRW-10522 Improvements for CI after MFA release.

cypress/e2e/yves/ssp-asset/ssp-asset.cy.ts, cypress/e2e/yves/ssp-service/ssp-service.cy.ts, cypress/fixtures/suite/backoffice/ssp-asset-management/dynamic-ssp-asset-management.json, cypress/fixtures/suite/yves/ssp-dashboard-management/dynamic-ssp-dashboard-management.json, cypress/fixtures/suite/yves/ssp-file-management/dynamic-ssp-file-management.json, cypress/support/pages/backoffice/ssp-asset-management/add/ssp-asset-add-page.ts, cypress/support/pages/backoffice/ssp-asset-management/detail/ssp-asset-detail-page.ts, cypress/support/pages/backoffice/ssp-asset-management/list/ssp-asset-list-page.ts, cypress/support/pages/backoffice/ssp-asset-management/list/ssp-asset-list-repository.ts, cypress/support/pages/backoffice/ssp-asset-management/update/ssp-asset-update-page.ts, cypress/support/pages/backoffice/ssp-file-management/add/ssp-file-management-add-page.ts, cypress/support/pages/backoffice/ssp-file-management/attach/ssp-file-management-attach-page.ts, cypress/support/pages/backoffice/ssp-file-management/list/ssp-file-management-list-page.ts, cypress/support/pages/backoffice/ssp-inquiry/ssp-inquiry-detail-page.ts, cypress/support/pages/backoffice/ssp-inquiry/ssp-inquiry-list-page.ts, cypress/support/pages/yves/ssp-asset/ssp-asset-create-page.ts, cypress/support/pages/yves/ssp-asset/ssp-asset-detail-page.ts, cypress/support/pages/yves/ssp-asset/ssp-asset-edit-page.ts, cypress/support/pages/yves/ssp-asset/ssp-asset-list-page.ts, cypress/support/pages/yves/ssp-file-management/ssp-file-management-download-page.ts, cypress/support/pages/yves/ssp-file-management/ssp-file-management-list-page.ts, cypress/support/pages/yves/ssp-service/ssp-service-list-page.ts
- Ticket: https://spryker.atlassian.net/browse/SSP-869
Reference all core PRs for auto-link back-references.
Core PRs
- https://github.com/spryker/spryker/pull/11556
- https://github.com/spryker/spryker-shop/pull/2665
=> SSP-869: Tech Debt Q2 backlog.

cypress/support/e2e.ts
=> Skipped queue cleanup.

cypress/e2e/backoffice/gift-cards/order-gift-card.cy.ts, cypress/fixtures/b2c-mp/backoffice/gift-cards/dynamic-order-gift-card.json, cypress/fixtures/b2c-mp/backoffice/gift-cards/static-order-gift-card.json, cypress/fixtures/b2c/backoffice/gift-cards/dynamic-order-gift-card.json, cypress/fixtures/b2c/backoffice/gift-cards/static-order-gift-card.json, cypress/fixtures/suite/backoffice/gift-cards/dynamic-order-gift-card.json, cypress/fixtures/suite/backoffice/gift-cards/static-order-gift-card.json, cypress/support/scenarios/yves/checkout-scenario.ts
=> CC-35578: Added test for gift-cards.

cypress/e2e/yves/order-amendment/order-amendment-start.cy.ts, cypress/fixtures/suite/yves/order-amendment/dynamic-order-amendment-start.json, cypress/support/types/yves/order-amendment.ts
Ticket: https://spryker.atlassian.net/browse/CC-34509
=> CC-34509 Adjusting Stock,Availability,Reservation behaviour during Order Amendment.

cypress/e2e/backoffice/product-measurement-unit/product-measurement-unit-create.cy.ts, cypress/e2e/backoffice/product-measurement-unit/product-measurement-unit-list.cy.ts
Measurement Unit GUI tests need to run for B2B and B2B-MP demoshops as well.
=> AE-212 Adjusted measurement unit gui tests to run for b2b and b2b-mp demoshops

cypress/e2e/mp/marketplace-agent-assist/agent-dashboard.cy.ts
Adjusted Agent Dashboard tests to make them more stable.
=> FRW-9814 Fixes for Agent Dashboard tests.

cypress/e2e/yves/ssp-asset/ssp-asset.cy.ts, cypress/support/pages/yves/ssp-dashboard-management/repositories/b2b-mp-ssp-dashboard-management-repository.ts, cypress/support/pages/yves/ssp-dashboard-management/repositories/suite-ssp-dashboard-management-repository.ts
=> SSP-595 Fixed Naming/Translations/Structure.

cypress/support/pages/yves/ssp-dashboard-management/repositories/b2b-mp-ssp-dashboard-management-repository.ts, cypress/support/pages/yves/ssp-dashboard-management/repositories/b2b-ssp-dashboard-management-repository.ts, cypress/support/pages/yves/ssp-dashboard-management/repositories/suite-ssp-dashboard-management-repository.ts
=> SSP-1380 Dashboard: Display Booked services.

cypress/e2e/smoke/order-management/dummy-payment-oms-flow.cy.ts, cypress/e2e/smoke/order-management/marketplace-payment-oms-flow.cy.ts
=> Adjusted smoke OMS tests.

cypress/support/pages/mp/sales/sales-orders-page.ts
=> Adjusted Merchant commissions test

cypress/support/pages/mp/sales/sales-orders-page.ts, cypress/support/pages/mp/sales/sales-orders-repository.ts
This PR contains a fix to make the flaky test "mp/marketplace-order-management/order-creation-dms.cy.ts" more stable.
Ticket: https://spryker.atlassian.net/browse/CC-36008
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are …
=> CC-36008: Flaky Cypress test. Order creation dms

cypress/e2e/yves/core/locale-switching.cy.ts
=> FRW-10805 Fixed locale switching test/

docker-compose.cypress.yml
=> Fixed docker-compose version.

cypress/e2e/mp/marketplace-agent-assist/agent-permission.cy.ts, cypress/support/pages/backoffice/user/update/user-update-page.ts
=> Fixed flaky test.

cypress/fixtures/b2b/backoffice/ssp-file-management/dynamic-ssp-file-management.json
=> SSP-1176: b2b integration

cypress/e2e/yves/ssp-asset/ssp-asset.cy.ts, cypress/support/pages/yves/product/product-page.ts, cypress/support/pages/yves/product/product-repository.ts, cypress/support/pages/yves/product/repositories/b2b-mp-product-repository.ts, cypress/support/pages/yves/product/repositories/b2b-product-repository.ts, cypress/support/pages/yves/product/repositories/b2c-mp-product-repository.ts, cypress/support/pages/yves/product/repositories/b2c-product-repository.ts, cypress/support/pages/yves/product/repositories/suite-product-repository.ts, cypress/support/types/yves/ssp-asset.ts
Ticket: https://spryker.atlassian.net/browse/SSP-1171  
TestCase: https://spryker.atlassian.net/wiki/spaces/SSP/pages/5101060469/Checklist+for+Asset+Models+Spare+Parts#Cart-Page-and-Checkout-Flow
BC-check: https://github.com/spryker/suite-nonsplit/pull/9972
=> SSP-1171 Added tests for Product->Asset selection functionality.
